// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto
package com.gettyio.protobuf.packet;
public final class MessageClass {
  private MessageClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Э���־
     * </pre>
     *
     * <code>optional string identify = 1;</code>
     */
    String getIdentify();
    /**
     * <pre>
     * Э���־
     * </pre>
     *
     * <code>optional string identify = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdentifyBytes();

    /**
     * <pre>
     * Э��汾
     * </pre>
     *
     * <code>optional string version = 2;</code>
     */
    String getVersion();
    /**
     * <pre>
     * Э��汾
     * </pre>
     *
     * <code>optional string version = 2;</code>
     */
    com.google.protobuf.ByteString
        getVersionBytes();

    /**
     * <pre>
     * ��������
     * </pre>
     *
     * <code>optional int32 reqType = 4;</code>
     */
    int getReqType();

    /**
     * <pre>
     *��Ϣʱ��
     * </pre>
     *
     * <code>optional int64 msgTime = 6;</code>
     */
    long getMsgTime();

    /**
     * <pre>
     *��ϢΨһID
     * </pre>
     *
     * <code>optional string id = 7;</code>
     */
    String getId();
    /**
     * <pre>
     *��ϢΨһID
     * </pre>
     *
     * <code>optional string id = 7;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <pre>
     *��������־
     * </pre>
     *
     * <code>optional string serverIdentify = 9;</code>
     */
    String getServerIdentify();
    /**
     * <pre>
     *��������־
     * </pre>
     *
     * <code>optional string serverIdentify = 9;</code>
     */
    com.google.protobuf.ByteString
        getServerIdentifyBytes();

    /**
     * <code>optional .google.protobuf.Any body = 8;</code>
     */
    boolean hasBody();
    /**
     * <code>optional .google.protobuf.Any body = 8;</code>
     */
    com.google.protobuf.Any getBody();
    /**
     * <code>optional .google.protobuf.Any body = 8;</code>
     */
    com.google.protobuf.AnyOrBuilder getBodyOrBuilder();
  }
  /**
   * Protobuf type {@code Message}
   */
  public  static final class Message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Message)
      MessageOrBuilder {
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message() {
      identify_ = "";
      version_ = "";
      reqType_ = 0;
      msgTime_ = 0L;
      id_ = "";
      serverIdentify_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              identify_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              version_ = s;
              break;
            }
            case 32: {

              reqType_ = input.readInt32();
              break;
            }
            case 48: {

              msgTime_ = input.readInt64();
              break;
            }
            case 58: {
              String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 66: {
              com.google.protobuf.Any.Builder subBuilder = null;
              if (body_ != null) {
                subBuilder = body_.toBuilder();
              }
              body_ = input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(body_);
                body_ = subBuilder.buildPartial();
              }

              break;
            }
            case 74: {
              String s = input.readStringRequireUtf8();

              serverIdentify_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MessageClass.internal_static_Message_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MessageClass.internal_static_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Message.class, Builder.class);
    }

    public static final int IDENTIFY_FIELD_NUMBER = 1;
    private volatile Object identify_;
    /**
     * <pre>
     * Э���־
     * </pre>
     *
     * <code>optional string identify = 1;</code>
     */
    public String getIdentify() {
      Object ref = identify_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        identify_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Э���־
     * </pre>
     *
     * <code>optional string identify = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdentifyBytes() {
      Object ref = identify_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        identify_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VERSION_FIELD_NUMBER = 2;
    private volatile Object version_;
    /**
     * <pre>
     * Э��汾
     * </pre>
     *
     * <code>optional string version = 2;</code>
     */
    public String getVersion() {
      Object ref = version_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        version_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Э��汾
     * </pre>
     *
     * <code>optional string version = 2;</code>
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      Object ref = version_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REQTYPE_FIELD_NUMBER = 4;
    private int reqType_;
    /**
     * <pre>
     * ��������
     * </pre>
     *
     * <code>optional int32 reqType = 4;</code>
     */
    public int getReqType() {
      return reqType_;
    }

    public static final int MSGTIME_FIELD_NUMBER = 6;
    private long msgTime_;
    /**
     * <pre>
     *��Ϣʱ��
     * </pre>
     *
     * <code>optional int64 msgTime = 6;</code>
     */
    public long getMsgTime() {
      return msgTime_;
    }

    public static final int ID_FIELD_NUMBER = 7;
    private volatile Object id_;
    /**
     * <pre>
     *��ϢΨһID
     * </pre>
     *
     * <code>optional string id = 7;</code>
     */
    public String getId() {
      Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *��ϢΨһID
     * </pre>
     *
     * <code>optional string id = 7;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SERVERIDENTIFY_FIELD_NUMBER = 9;
    private volatile Object serverIdentify_;
    /**
     * <pre>
     *��������־
     * </pre>
     *
     * <code>optional string serverIdentify = 9;</code>
     */
    public String getServerIdentify() {
      Object ref = serverIdentify_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        serverIdentify_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *��������־
     * </pre>
     *
     * <code>optional string serverIdentify = 9;</code>
     */
    public com.google.protobuf.ByteString
        getServerIdentifyBytes() {
      Object ref = serverIdentify_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        serverIdentify_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BODY_FIELD_NUMBER = 8;
    private com.google.protobuf.Any body_;
    /**
     * <code>optional .google.protobuf.Any body = 8;</code>
     */
    public boolean hasBody() {
      return body_ != null;
    }
    /**
     * <code>optional .google.protobuf.Any body = 8;</code>
     */
    public com.google.protobuf.Any getBody() {
      return body_ == null ? com.google.protobuf.Any.getDefaultInstance() : body_;
    }
    /**
     * <code>optional .google.protobuf.Any body = 8;</code>
     */
    public com.google.protobuf.AnyOrBuilder getBodyOrBuilder() {
      return getBody();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdentifyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, identify_);
      }
      if (!getVersionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, version_);
      }
      if (reqType_ != 0) {
        output.writeInt32(4, reqType_);
      }
      if (msgTime_ != 0L) {
        output.writeInt64(6, msgTime_);
      }
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, id_);
      }
      if (body_ != null) {
        output.writeMessage(8, getBody());
      }
      if (!getServerIdentifyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, serverIdentify_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdentifyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, identify_);
      }
      if (!getVersionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, version_);
      }
      if (reqType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, reqType_);
      }
      if (msgTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, msgTime_);
      }
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, id_);
      }
      if (body_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, getBody());
      }
      if (!getServerIdentifyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, serverIdentify_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Message)) {
        return super.equals(obj);
      }
      Message other = (Message) obj;

      boolean result = true;
      result = result && getIdentify()
          .equals(other.getIdentify());
      result = result && getVersion()
          .equals(other.getVersion());
      result = result && (getReqType()
          == other.getReqType());
      result = result && (getMsgTime()
          == other.getMsgTime());
      result = result && getId()
          .equals(other.getId());
      result = result && getServerIdentify()
          .equals(other.getServerIdentify());
      result = result && (hasBody() == other.hasBody());
      if (hasBody()) {
        result = result && getBody()
            .equals(other.getBody());
      }
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + IDENTIFY_FIELD_NUMBER;
      hash = (53 * hash) + getIdentify().hashCode();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion().hashCode();
      hash = (37 * hash) + REQTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getReqType();
      hash = (37 * hash) + MSGTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMsgTime());
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + SERVERIDENTIFY_FIELD_NUMBER;
      hash = (53 * hash) + getServerIdentify().hashCode();
      if (hasBody()) {
        hash = (37 * hash) + BODY_FIELD_NUMBER;
        hash = (53 * hash) + getBody().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Message)
        MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MessageClass.internal_static_Message_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MessageClass.internal_static_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Message.class, Builder.class);
      }

      // Construct using MessageClass.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        identify_ = "";

        version_ = "";

        reqType_ = 0;

        msgTime_ = 0L;

        id_ = "";

        serverIdentify_ = "";

        if (bodyBuilder_ == null) {
          body_ = null;
        } else {
          body_ = null;
          bodyBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MessageClass.internal_static_Message_descriptor;
      }

      public Message getDefaultInstanceForType() {
        return Message.getDefaultInstance();
      }

      public Message build() {
        Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Message buildPartial() {
        Message result = new Message(this);
        result.identify_ = identify_;
        result.version_ = version_;
        result.reqType_ = reqType_;
        result.msgTime_ = msgTime_;
        result.id_ = id_;
        result.serverIdentify_ = serverIdentify_;
        if (bodyBuilder_ == null) {
          result.body_ = body_;
        } else {
          result.body_ = bodyBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Message) {
          return mergeFrom((Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Message other) {
        if (other == Message.getDefaultInstance()) return this;
        if (!other.getIdentify().isEmpty()) {
          identify_ = other.identify_;
          onChanged();
        }
        if (!other.getVersion().isEmpty()) {
          version_ = other.version_;
          onChanged();
        }
        if (other.getReqType() != 0) {
          setReqType(other.getReqType());
        }
        if (other.getMsgTime() != 0L) {
          setMsgTime(other.getMsgTime());
        }
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getServerIdentify().isEmpty()) {
          serverIdentify_ = other.serverIdentify_;
          onChanged();
        }
        if (other.hasBody()) {
          mergeBody(other.getBody());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Message) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object identify_ = "";
      /**
       * <pre>
       * Э���־
       * </pre>
       *
       * <code>optional string identify = 1;</code>
       */
      public String getIdentify() {
        Object ref = identify_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          identify_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * Э���־
       * </pre>
       *
       * <code>optional string identify = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdentifyBytes() {
        Object ref = identify_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          identify_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Э���־
       * </pre>
       *
       * <code>optional string identify = 1;</code>
       */
      public Builder setIdentify(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        identify_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Э���־
       * </pre>
       *
       * <code>optional string identify = 1;</code>
       */
      public Builder clearIdentify() {
        
        identify_ = getDefaultInstance().getIdentify();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Э���־
       * </pre>
       *
       * <code>optional string identify = 1;</code>
       */
      public Builder setIdentifyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        identify_ = value;
        onChanged();
        return this;
      }

      private Object version_ = "";
      /**
       * <pre>
       * Э��汾
       * </pre>
       *
       * <code>optional string version = 2;</code>
       */
      public String getVersion() {
        Object ref = version_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          version_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * Э��汾
       * </pre>
       *
       * <code>optional string version = 2;</code>
       */
      public com.google.protobuf.ByteString
          getVersionBytes() {
        Object ref = version_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          version_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Э��汾
       * </pre>
       *
       * <code>optional string version = 2;</code>
       */
      public Builder setVersion(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Э��汾
       * </pre>
       *
       * <code>optional string version = 2;</code>
       */
      public Builder clearVersion() {
        
        version_ = getDefaultInstance().getVersion();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Э��汾
       * </pre>
       *
       * <code>optional string version = 2;</code>
       */
      public Builder setVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        version_ = value;
        onChanged();
        return this;
      }

      private int reqType_ ;
      /**
       * <pre>
       * ��������
       * </pre>
       *
       * <code>optional int32 reqType = 4;</code>
       */
      public int getReqType() {
        return reqType_;
      }
      /**
       * <pre>
       * ��������
       * </pre>
       *
       * <code>optional int32 reqType = 4;</code>
       */
      public Builder setReqType(int value) {
        
        reqType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * ��������
       * </pre>
       *
       * <code>optional int32 reqType = 4;</code>
       */
      public Builder clearReqType() {
        
        reqType_ = 0;
        onChanged();
        return this;
      }

      private long msgTime_ ;
      /**
       * <pre>
       *��Ϣʱ��
       * </pre>
       *
       * <code>optional int64 msgTime = 6;</code>
       */
      public long getMsgTime() {
        return msgTime_;
      }
      /**
       * <pre>
       *��Ϣʱ��
       * </pre>
       *
       * <code>optional int64 msgTime = 6;</code>
       */
      public Builder setMsgTime(long value) {
        
        msgTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *��Ϣʱ��
       * </pre>
       *
       * <code>optional int64 msgTime = 6;</code>
       */
      public Builder clearMsgTime() {
        
        msgTime_ = 0L;
        onChanged();
        return this;
      }

      private Object id_ = "";
      /**
       * <pre>
       *��ϢΨһID
       * </pre>
       *
       * <code>optional string id = 7;</code>
       */
      public String getId() {
        Object ref = id_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *��ϢΨһID
       * </pre>
       *
       * <code>optional string id = 7;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *��ϢΨһID
       * </pre>
       *
       * <code>optional string id = 7;</code>
       */
      public Builder setId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *��ϢΨһID
       * </pre>
       *
       * <code>optional string id = 7;</code>
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *��ϢΨһID
       * </pre>
       *
       * <code>optional string id = 7;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private Object serverIdentify_ = "";
      /**
       * <pre>
       *��������־
       * </pre>
       *
       * <code>optional string serverIdentify = 9;</code>
       */
      public String getServerIdentify() {
        Object ref = serverIdentify_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          serverIdentify_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *��������־
       * </pre>
       *
       * <code>optional string serverIdentify = 9;</code>
       */
      public com.google.protobuf.ByteString
          getServerIdentifyBytes() {
        Object ref = serverIdentify_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          serverIdentify_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *��������־
       * </pre>
       *
       * <code>optional string serverIdentify = 9;</code>
       */
      public Builder setServerIdentify(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        serverIdentify_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *��������־
       * </pre>
       *
       * <code>optional string serverIdentify = 9;</code>
       */
      public Builder clearServerIdentify() {
        
        serverIdentify_ = getDefaultInstance().getServerIdentify();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *��������־
       * </pre>
       *
       * <code>optional string serverIdentify = 9;</code>
       */
      public Builder setServerIdentifyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        serverIdentify_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.Any body_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> bodyBuilder_;
      /**
       * <code>optional .google.protobuf.Any body = 8;</code>
       */
      public boolean hasBody() {
        return bodyBuilder_ != null || body_ != null;
      }
      /**
       * <code>optional .google.protobuf.Any body = 8;</code>
       */
      public com.google.protobuf.Any getBody() {
        if (bodyBuilder_ == null) {
          return body_ == null ? com.google.protobuf.Any.getDefaultInstance() : body_;
        } else {
          return bodyBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .google.protobuf.Any body = 8;</code>
       */
      public Builder setBody(com.google.protobuf.Any value) {
        if (bodyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          body_ = value;
          onChanged();
        } else {
          bodyBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.Any body = 8;</code>
       */
      public Builder setBody(
          com.google.protobuf.Any.Builder builderForValue) {
        if (bodyBuilder_ == null) {
          body_ = builderForValue.build();
          onChanged();
        } else {
          bodyBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.Any body = 8;</code>
       */
      public Builder mergeBody(com.google.protobuf.Any value) {
        if (bodyBuilder_ == null) {
          if (body_ != null) {
            body_ =
              com.google.protobuf.Any.newBuilder(body_).mergeFrom(value).buildPartial();
          } else {
            body_ = value;
          }
          onChanged();
        } else {
          bodyBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.Any body = 8;</code>
       */
      public Builder clearBody() {
        if (bodyBuilder_ == null) {
          body_ = null;
          onChanged();
        } else {
          body_ = null;
          bodyBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .google.protobuf.Any body = 8;</code>
       */
      public com.google.protobuf.Any.Builder getBodyBuilder() {
        
        onChanged();
        return getBodyFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .google.protobuf.Any body = 8;</code>
       */
      public com.google.protobuf.AnyOrBuilder getBodyOrBuilder() {
        if (bodyBuilder_ != null) {
          return bodyBuilder_.getMessageOrBuilder();
        } else {
          return body_ == null ?
              com.google.protobuf.Any.getDefaultInstance() : body_;
        }
      }
      /**
       * <code>optional .google.protobuf.Any body = 8;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
          getBodyFieldBuilder() {
        if (bodyBuilder_ == null) {
          bodyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                  getBody(),
                  getParentForChildren(),
                  isClean());
          body_ = null;
        }
        return bodyBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Message)
    }

    // @@protoc_insertion_point(class_scope:Message)
    private static final Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Message();
    }

    public static Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Message(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    public Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rMessage.proto\032\031google/protobuf/any.pro" +
      "to\"\226\001\n\007Message\022\020\n\010identify\030\001 \001(\t\022\017\n\007vers" +
      "ion\030\002 \001(\t\022\017\n\007reqType\030\004 \001(\005\022\017\n\007msgTime\030\006 " +
      "\001(\003\022\n\n\002id\030\007 \001(\t\022\026\n\016serverIdentify\030\t \001(\t\022" +
      "\"\n\004body\030\010 \001(\0132\024.google.protobuf.AnyB\016B\014M" +
      "essageClassb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        }, assigner);
    internal_static_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_descriptor,
        new String[] { "Identify", "Version", "ReqType", "MsgTime", "Id", "ServerIdentify", "Body", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
