// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SingleChatReq.proto
package com.gettyio.test.packet;

public final class SingleChatReqClass {
	private SingleChatReqClass() {
	}

	public static void registerAllExtensions(
			com.google.protobuf.ExtensionRegistryLite registry) {
	}

	public static void registerAllExtensions(
			com.google.protobuf.ExtensionRegistry registry) {
		registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
	}

	public interface SingleChatReqOrBuilder extends
	// @@protoc_insertion_point(interface_extends:SingleChatReq)
			com.google.protobuf.MessageOrBuilder {

		/**
		 * <pre>
		 * ������ID
		 * </pre>
		 *
		 * <code>optional string senderId = 1;</code>
		 */
		String getSenderId();

		/**
		 * <pre>
		 * ������ID
		 * </pre>
		 *
		 * <code>optional string senderId = 1;</code>
		 */
		com.google.protobuf.ByteString getSenderIdBytes();

		/**
		 * <pre>
		 * ������ID
		 * </pre>
		 *
		 * <code>optional string receiverId = 2;</code>
		 */
		String getReceiverId();

		/**
		 * <pre>
		 * ������ID
		 * </pre>
		 *
		 * <code>optional string receiverId = 2;</code>
		 */
		com.google.protobuf.ByteString getReceiverIdBytes();

		/**
		 * <pre>
		 * ��Ϣ����
		 * </pre>
		 *
		 * <code>optional int32 msgType = 3;</code>
		 */
		int getMsgType();

		/**
		 * <pre>
		 * ��Ϣ��
		 * </pre>
		 *
		 * <code>optional string body = 4;</code>
		 */
		String getBody();

		/**
		 * <pre>
		 * ��Ϣ��
		 * </pre>
		 *
		 * <code>optional string body = 4;</code>
		 */
		com.google.protobuf.ByteString getBodyBytes();
	}

	/**
	 * Protobuf type {@code SingleChatReq}
	 */
	public static final class SingleChatReq extends
			com.google.protobuf.GeneratedMessageV3 implements
	// @@protoc_insertion_point(message_implements:SingleChatReq)
			SingleChatReqOrBuilder {
		// Use SingleChatReq.newBuilder() to construct.
		private SingleChatReq(
				com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
			super(builder);
		}

		private SingleChatReq() {
			senderId_ = "";
			receiverId_ = "";
			msgType_ = 0;
			body_ = "";
		}

		@Override
		public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
			return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
		}

		private SingleChatReq(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			this();
			int mutable_bitField0_ = 0;
			try {
				boolean done = false;
				while (!done) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						done = true;
						break;
					default: {
						if (!input.skipField(tag)) {
							done = true;
						}
						break;
					}
					case 10: {
						String s = input.readStringRequireUtf8();

						senderId_ = s;
						break;
					}
					case 18: {
						String s = input.readStringRequireUtf8();

						receiverId_ = s;
						break;
					}
					case 24: {

						msgType_ = input.readInt32();
						break;
					}
					case 34: {
						String s = input.readStringRequireUtf8();

						body_ = s;
						break;
					}
					}
				}
			} catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.setUnfinishedMessage(this);
			} catch (java.io.IOException e) {
				throw new com.google.protobuf.InvalidProtocolBufferException(e)
						.setUnfinishedMessage(this);
			} finally {
				makeExtensionsImmutable();
			}
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return SingleChatReqClass.internal_static_SingleChatReq_descriptor;
		}

		protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
			return SingleChatReqClass.internal_static_SingleChatReq_fieldAccessorTable
					.ensureFieldAccessorsInitialized(
							SingleChatReq.class,
							Builder.class);
		}

		public static final int SENDERID_FIELD_NUMBER = 1;
		private volatile Object senderId_;

		/**
		 * <pre>
		 * ������ID
		 * </pre>
		 *
		 * <code>optional string senderId = 1;</code>
		 */
		public String getSenderId() {
			Object ref = senderId_;
			if (ref instanceof String) {
				return (String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				senderId_ = s;
				return s;
			}
		}

		/**
		 * <pre>
		 * ������ID
		 * </pre>
		 *
		 * <code>optional string senderId = 1;</code>
		 */
		public com.google.protobuf.ByteString getSenderIdBytes() {
			Object ref = senderId_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString
						.copyFromUtf8((String) ref);
				senderId_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		public static final int RECEIVERID_FIELD_NUMBER = 2;
		private volatile Object receiverId_;

		/**
		 * <pre>
		 * ������ID
		 * </pre>
		 *
		 * <code>optional string receiverId = 2;</code>
		 */
		public String getReceiverId() {
			Object ref = receiverId_;
			if (ref instanceof String) {
				return (String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				receiverId_ = s;
				return s;
			}
		}

		/**
		 * <pre>
		 * ������ID
		 * </pre>
		 *
		 * <code>optional string receiverId = 2;</code>
		 */
		public com.google.protobuf.ByteString getReceiverIdBytes() {
			Object ref = receiverId_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString
						.copyFromUtf8((String) ref);
				receiverId_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		public static final int MSGTYPE_FIELD_NUMBER = 3;
		private int msgType_;

		/**
		 * <pre>
		 * ��Ϣ����
		 * </pre>
		 *
		 * <code>optional int32 msgType = 3;</code>
		 */
		public int getMsgType() {
			return msgType_;
		}

		public static final int BODY_FIELD_NUMBER = 4;
		private volatile Object body_;

		/**
		 * <pre>
		 * ��Ϣ��
		 * </pre>
		 *
		 * <code>optional string body = 4;</code>
		 */
		public String getBody() {
			Object ref = body_;
			if (ref instanceof String) {
				return (String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				body_ = s;
				return s;
			}
		}

		/**
		 * <pre>
		 * ��Ϣ��
		 * </pre>
		 *
		 * <code>optional string body = 4;</code>
		 */
		public com.google.protobuf.ByteString getBodyBytes() {
			Object ref = body_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString
						.copyFromUtf8((String) ref);
				body_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		private byte memoizedIsInitialized = -1;

		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized == 1)
				return true;
			if (isInitialized == 0)
				return false;

			memoizedIsInitialized = 1;
			return true;
		}

		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			if (!getSenderIdBytes().isEmpty()) {
				com.google.protobuf.GeneratedMessageV3.writeString(output, 1,
						senderId_);
			}
			if (!getReceiverIdBytes().isEmpty()) {
				com.google.protobuf.GeneratedMessageV3.writeString(output, 2,
						receiverId_);
			}
			if (msgType_ != 0) {
				output.writeInt32(3, msgType_);
			}
			if (!getBodyBytes().isEmpty()) {
				com.google.protobuf.GeneratedMessageV3.writeString(output, 4,
						body_);
			}
		}

		public int getSerializedSize() {
			int size = memoizedSize;
			if (size != -1)
				return size;

			size = 0;
			if (!getSenderIdBytes().isEmpty()) {
				size += com.google.protobuf.GeneratedMessageV3
						.computeStringSize(1, senderId_);
			}
			if (!getReceiverIdBytes().isEmpty()) {
				size += com.google.protobuf.GeneratedMessageV3
						.computeStringSize(2, receiverId_);
			}
			if (msgType_ != 0) {
				size += com.google.protobuf.CodedOutputStream.computeInt32Size(
						3, msgType_);
			}
			if (!getBodyBytes().isEmpty()) {
				size += com.google.protobuf.GeneratedMessageV3
						.computeStringSize(4, body_);
			}
			memoizedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;

		@Override
		public boolean equals(final Object obj) {
			if (obj == this) {
				return true;
			}
			if (!(obj instanceof SingleChatReq)) {
				return super.equals(obj);
			}
			SingleChatReq other = (SingleChatReq) obj;

			boolean result = true;
			result = result && getSenderId().equals(other.getSenderId());
			result = result && getReceiverId().equals(other.getReceiverId());
			result = result && (getMsgType() == other.getMsgType());
			result = result && getBody().equals(other.getBody());
			return result;
		}

		@Override
		public int hashCode() {
			if (memoizedHashCode != 0) {
				return memoizedHashCode;
			}
			int hash = 41;
			hash = (19 * hash) + getDescriptorForType().hashCode();
			hash = (37 * hash) + SENDERID_FIELD_NUMBER;
			hash = (53 * hash) + getSenderId().hashCode();
			hash = (37 * hash) + RECEIVERID_FIELD_NUMBER;
			hash = (53 * hash) + getReceiverId().hashCode();
			hash = (37 * hash) + MSGTYPE_FIELD_NUMBER;
			hash = (53 * hash) + getMsgType();
			hash = (37 * hash) + BODY_FIELD_NUMBER;
			hash = (53 * hash) + getBody().hashCode();
			hash = (29 * hash) + unknownFields.hashCode();
			memoizedHashCode = hash;
			return hash;
		}

		public static SingleChatReq parseFrom(
				com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static SingleChatReq parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static SingleChatReq parseFrom(byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static SingleChatReq parseFrom(byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static SingleChatReq parseFrom(
				java.io.InputStream input) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
					PARSER, input);
		}

		public static SingleChatReq parseFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
					PARSER, input, extensionRegistry);
		}

		public static SingleChatReq parseDelimitedFrom(
				java.io.InputStream input) throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
					.parseDelimitedWithIOException(PARSER, input);
		}

		public static SingleChatReq parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
					.parseDelimitedWithIOException(PARSER, input,
							extensionRegistry);
		}

		public static SingleChatReq parseFrom(
				com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
					PARSER, input);
		}

		public static SingleChatReq parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
					PARSER, input, extensionRegistry);
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder() {
			return DEFAULT_INSTANCE.toBuilder();
		}

		public static Builder newBuilder(
				SingleChatReq prototype) {
			return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
		}

		public Builder toBuilder() {
			return this == DEFAULT_INSTANCE ? new Builder() : new Builder()
					.mergeFrom(this);
		}

		@Override
		protected Builder newBuilderForType(
				com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		/**
		 * Protobuf type {@code SingleChatReq}
		 */
		public static final class Builder extends
				com.google.protobuf.GeneratedMessageV3.Builder<Builder>
				implements
				// @@protoc_insertion_point(builder_implements:SingleChatReq)
				SingleChatReqOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return SingleChatReqClass.internal_static_SingleChatReq_descriptor;
			}

			protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
				return SingleChatReqClass.internal_static_SingleChatReq_fieldAccessorTable
						.ensureFieldAccessorsInitialized(
								SingleChatReq.class,
								Builder.class);
			}

			// Construct using SingleChatReqClass.SingleChatReq.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(
					com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
				}
			}

			public Builder clear() {
				super.clear();
				senderId_ = "";

				receiverId_ = "";

				msgType_ = 0;

				body_ = "";

				return this;
			}

			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return SingleChatReqClass.internal_static_SingleChatReq_descriptor;
			}

			public SingleChatReq getDefaultInstanceForType() {
				return SingleChatReq.getDefaultInstance();
			}

			public SingleChatReq build() {
				SingleChatReq result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			public SingleChatReq buildPartial() {
				SingleChatReq result = new SingleChatReq(
						this);
				result.senderId_ = senderId_;
				result.receiverId_ = receiverId_;
				result.msgType_ = msgType_;
				result.body_ = body_;
				onBuilt();
				return result;
			}

			public Builder clone() {
				return (Builder) super.clone();
			}

			public Builder setField(
					com.google.protobuf.Descriptors.FieldDescriptor field,
					Object value) {
				return (Builder) super.setField(field, value);
			}

			public Builder clearField(
					com.google.protobuf.Descriptors.FieldDescriptor field) {
				return (Builder) super.clearField(field);
			}

			public Builder clearOneof(
					com.google.protobuf.Descriptors.OneofDescriptor oneof) {
				return (Builder) super.clearOneof(oneof);
			}

			public Builder setRepeatedField(
					com.google.protobuf.Descriptors.FieldDescriptor field,
					int index, Object value) {
				return (Builder) super.setRepeatedField(field, index, value);
			}

			public Builder addRepeatedField(
					com.google.protobuf.Descriptors.FieldDescriptor field,
					Object value) {
				return (Builder) super.addRepeatedField(field, value);
			}

			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof SingleChatReq) {
					return mergeFrom((SingleChatReq) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(SingleChatReq other) {
				if (other == SingleChatReq
						.getDefaultInstance())
					return this;
				if (!other.getSenderId().isEmpty()) {
					senderId_ = other.senderId_;
					onChanged();
				}
				if (!other.getReceiverId().isEmpty()) {
					receiverId_ = other.receiverId_;
					onChanged();
				}
				if (other.getMsgType() != 0) {
					setMsgType(other.getMsgType());
				}
				if (!other.getBody().isEmpty()) {
					body_ = other.body_;
					onChanged();
				}
				onChanged();
				return this;
			}

			public final boolean isInitialized() {
				return true;
			}

			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				SingleChatReq parsedMessage = null;
				try {
					parsedMessage = PARSER.parsePartialFrom(input,
							extensionRegistry);
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					parsedMessage = (SingleChatReq) e
							.getUnfinishedMessage();
					throw e.unwrapIOException();
				} finally {
					if (parsedMessage != null) {
						mergeFrom(parsedMessage);
					}
				}
				return this;
			}

			private Object senderId_ = "";

			/**
			 * <pre>
			 * ������ID
			 * </pre>
			 *
			 * <code>optional string senderId = 1;</code>
			 */
			public String getSenderId() {
				Object ref = senderId_;
				if (!(ref instanceof String)) {
					com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
					String s = bs.toStringUtf8();
					senderId_ = s;
					return s;
				} else {
					return (String) ref;
				}
			}

			/**
			 * <pre>
			 * ������ID
			 * </pre>
			 *
			 * <code>optional string senderId = 1;</code>
			 */
			public com.google.protobuf.ByteString getSenderIdBytes() {
				Object ref = senderId_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString
							.copyFromUtf8((String) ref);
					senderId_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <pre>
			 * ������ID
			 * </pre>
			 *
			 * <code>optional string senderId = 1;</code>
			 */
			public Builder setSenderId(String value) {
				if (value == null) {
					throw new NullPointerException();
				}

				senderId_ = value;
				onChanged();
				return this;
			}

			/**
			 * <pre>
			 * ������ID
			 * </pre>
			 *
			 * <code>optional string senderId = 1;</code>
			 */
			public Builder clearSenderId() {

				senderId_ = getDefaultInstance().getSenderId();
				onChanged();
				return this;
			}

			/**
			 * <pre>
			 * ������ID
			 * </pre>
			 *
			 * <code>optional string senderId = 1;</code>
			 */
			public Builder setSenderIdBytes(com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				checkByteStringIsUtf8(value);

				senderId_ = value;
				onChanged();
				return this;
			}

			private Object receiverId_ = "";

			/**
			 * <pre>
			 * ������ID
			 * </pre>
			 *
			 * <code>optional string receiverId = 2;</code>
			 */
			public String getReceiverId() {
				Object ref = receiverId_;
				if (!(ref instanceof String)) {
					com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
					String s = bs.toStringUtf8();
					receiverId_ = s;
					return s;
				} else {
					return (String) ref;
				}
			}

			/**
			 * <pre>
			 * ������ID
			 * </pre>
			 *
			 * <code>optional string receiverId = 2;</code>
			 */
			public com.google.protobuf.ByteString getReceiverIdBytes() {
				Object ref = receiverId_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString
							.copyFromUtf8((String) ref);
					receiverId_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <pre>
			 * ������ID
			 * </pre>
			 *
			 * <code>optional string receiverId = 2;</code>
			 */
			public Builder setReceiverId(String value) {
				if (value == null) {
					throw new NullPointerException();
				}

				receiverId_ = value;
				onChanged();
				return this;
			}

			/**
			 * <pre>
			 * ������ID
			 * </pre>
			 *
			 * <code>optional string receiverId = 2;</code>
			 */
			public Builder clearReceiverId() {

				receiverId_ = getDefaultInstance().getReceiverId();
				onChanged();
				return this;
			}

			/**
			 * <pre>
			 * ������ID
			 * </pre>
			 *
			 * <code>optional string receiverId = 2;</code>
			 */
			public Builder setReceiverIdBytes(
					com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				checkByteStringIsUtf8(value);

				receiverId_ = value;
				onChanged();
				return this;
			}

			private int msgType_;

			/**
			 * <pre>
			 * ��Ϣ����
			 * </pre>
			 *
			 * <code>optional int32 msgType = 3;</code>
			 */
			public int getMsgType() {
				return msgType_;
			}

			/**
			 * <pre>
			 * ��Ϣ����
			 * </pre>
			 *
			 * <code>optional int32 msgType = 3;</code>
			 */
			public Builder setMsgType(int value) {

				msgType_ = value;
				onChanged();
				return this;
			}

			/**
			 * <pre>
			 * ��Ϣ����
			 * </pre>
			 *
			 * <code>optional int32 msgType = 3;</code>
			 */
			public Builder clearMsgType() {

				msgType_ = 0;
				onChanged();
				return this;
			}

			private Object body_ = "";

			/**
			 * <pre>
			 * ��Ϣ��
			 * </pre>
			 *
			 * <code>optional string body = 4;</code>
			 */
			public String getBody() {
				Object ref = body_;
				if (!(ref instanceof String)) {
					com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
					String s = bs.toStringUtf8();
					body_ = s;
					return s;
				} else {
					return (String) ref;
				}
			}

			/**
			 * <pre>
			 * ��Ϣ��
			 * </pre>
			 *
			 * <code>optional string body = 4;</code>
			 */
			public com.google.protobuf.ByteString getBodyBytes() {
				Object ref = body_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString
							.copyFromUtf8((String) ref);
					body_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <pre>
			 * ��Ϣ��
			 * </pre>
			 *
			 * <code>optional string body = 4;</code>
			 */
			public Builder setBody(String value) {
				if (value == null) {
					throw new NullPointerException();
				}

				body_ = value;
				onChanged();
				return this;
			}

			/**
			 * <pre>
			 * ��Ϣ��
			 * </pre>
			 *
			 * <code>optional string body = 4;</code>
			 */
			public Builder clearBody() {

				body_ = getDefaultInstance().getBody();
				onChanged();
				return this;
			}

			/**
			 * <pre>
			 * ��Ϣ��
			 * </pre>
			 *
			 * <code>optional string body = 4;</code>
			 */
			public Builder setBodyBytes(com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				checkByteStringIsUtf8(value);

				body_ = value;
				onChanged();
				return this;
			}

			public final Builder setUnknownFields(
					final com.google.protobuf.UnknownFieldSet unknownFields) {
				return this;
			}

			public final Builder mergeUnknownFields(
					final com.google.protobuf.UnknownFieldSet unknownFields) {
				return this;
			}

			// @@protoc_insertion_point(builder_scope:SingleChatReq)
		}

		// @@protoc_insertion_point(class_scope:SingleChatReq)
		private static final SingleChatReq DEFAULT_INSTANCE;
		static {
			DEFAULT_INSTANCE = new SingleChatReq();
		}

		public static SingleChatReq getDefaultInstance() {
			return DEFAULT_INSTANCE;
		}

		private static final com.google.protobuf.Parser<SingleChatReq> PARSER = new com.google.protobuf.AbstractParser<SingleChatReq>() {
			public SingleChatReq parsePartialFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return new SingleChatReq(input, extensionRegistry);
			}
		};

		public static com.google.protobuf.Parser<SingleChatReq> parser() {
			return PARSER;
		}

		@Override
		public com.google.protobuf.Parser<SingleChatReq> getParserForType() {
			return PARSER;
		}

		public SingleChatReq getDefaultInstanceForType() {
			return DEFAULT_INSTANCE;
		}

	}

	private static final com.google.protobuf.Descriptors.Descriptor internal_static_SingleChatReq_descriptor;
	private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_SingleChatReq_fieldAccessorTable;

	public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
		return descriptor;
	}

	private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
	static {
		String[] descriptorData = { "\n\023SingleChatReq.proto\"T\n\rSingleChatReq\022\020"
				+ "\n\010senderId\030\001 \001(\t\022\022\n\nreceiverId\030\002 \001(\t\022\017\n\007"
				+ "msgType\030\003 \001(\005\022\014\n\004body\030\004 \001(\tB\024B\022SingleCha"
				+ "tReqClassb\006proto3" };
		com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
			public com.google.protobuf.ExtensionRegistry assignDescriptors(
					com.google.protobuf.Descriptors.FileDescriptor root) {
				descriptor = root;
				return null;
			}
		};
		com.google.protobuf.Descriptors.FileDescriptor
				.internalBuildGeneratedFileFrom(
						descriptorData,
						new com.google.protobuf.Descriptors.FileDescriptor[] {},
						assigner);
		internal_static_SingleChatReq_descriptor = getDescriptor()
				.getMessageTypes().get(0);
		internal_static_SingleChatReq_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
				internal_static_SingleChatReq_descriptor,
				new String[] { "SenderId", "ReceiverId", "MsgType",
						"Body", });
	}

	// @@protoc_insertion_point(outer_class_scope)
}
